name: 'Fetch and verify Render deploy'
description: 'This action fetches Render deploy links from PR and verifies for a successful deployment of the deloyment preview'
inputs:
  token:
    description: 'GitHub Token'
    required: true
  render-email:
    description: 'Render Email'
    required: true
  render-password:
    description: 'Render Password'
    required: true
  sleep:
    required: false
    description: Sleep time between the render deployment success and setting the Github deployment as successful
    default: '0'
  retries:
    required: false
    description: 'Maximum number of retries trying to find the deployment. Note: Retries will be attempted every 5 seconds'
    default: '50'
  wait:
    required: false
    description: Sleep time between retries to find Render deployments statuses
    default: '8000'
outputs:
  preview-url:
    description: 'Successful Render deploy preview url'
runs:
  using: 'node16'
  main: dist/index.js